services:
  nginx:
    image: registry.cn-beijing.aliyuncs.com/qqlx/nginx:1.28.0-otel
    container_name: nginx-otel
    environment:
      - TZ="Asia/Shanghai"
    cap_add:
      - SYS_NICE
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/cert/:/etc/nginx/cert:ro
      - /data/html/:/data/html:ro
  apiserver:
    image: registry.cn-beijing.aliyuncs.com/qqlx/api-server:main-1a698df-20250918-155247
    restart: always
    container_name: apiserver
    # command: ["init"]
    environment:
      - TZ="Asia/Shanghai"
      - SERVICE_NAME=api-server
      - API_SERVER_SERVER_BIND=:8080
      - API_SERVER_CONFIG_PATH=/app/config.yaml
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://10.10.10.10:30001
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=api-server
      # - OTEL_METRICS_EXPORTER=prometheus
      # - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      # - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml

  redis:
    image: registry.cn-beijing.aliyuncs.com/middleware1995/redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --requirepass 123456
      --appendonly yes
      --save 86400 1

volumes:
  redis-data:
