services:
  apiserver:
    image: api-server
    restart: always
    container_name: apiserver
    environment:
      - TZ=Asia/Shanghai
      - SERVICE_NAME=api-server
      - API_SERVER_SERVER_BIND=:8080
      - CONFIG_PATH=/app/config.yaml
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://10.10.10.10:30001
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_SERVICE_NAME=api-server
      # - OTEL_METRICS_EXPORTER=prometheus
      # - OTEL_EXPORTER_PROMETHEUS_PORT=9464
      # - OTEL_EXPORTER_PROMETHEUS_HOST=0.0.0.0
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml

  redis:
    image: registry.cn-beijing.aliyuncs.com/middleware1995/redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server
      --requirepass 123456
      --appendonly yes
      --save 86400 1

volumes:
  redis-data:
