name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Image Tag
        id: vars
        run: |
          BRANCH=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's#[/ ]#-#g')
          SHORT_SHA=$(git rev-parse --short=7 HEAD)
          DATE=$(date +'%Y%m%d-%H%M%S')
          IMAGE_TAG="${BRANCH}-${SHORT_SHA}-${DATE}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Generated tag: $IMAGE_TAG"

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_HUB }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_HUB }}/qqlx/api-server:${{ env.IMAGE_TAG }}

      - name: Output Image Info
        run: |
          echo "Image pushed: ${{ vars.DOCKER_HUB }}/qqlx/api-server:${{ env.IMAGE_TAG }}"
